# Generated by Django 6.0.6 on 2026-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "total_recharge",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "recharge_profit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
