# Generated by Django 6.0.6 on 2026-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("expense_name", models.CharField(max_length=100)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct Expense"),
                            ("INDIRECT", "Indirect Expense"),
                            ("FOOD", "Food"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
