# Generated by Django 6.0.6 on 2026-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("code", models.CharField(max_length=10)),
                ("code_value", models.IntegerField(default=0)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("GPAY", "GPay")], max_length=10
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
