# Generated by Django 6.0.6 on 2026-06-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="product_name",
            field=models.CharField(default="Unknown Product", max_length=100),
        ),
    ]
